### ISSUE TITLE
Video carousel improvements

### ISSUE THREAD

**Issue by elijahhampton** [Nate-farley/pure-life-pools#1]
- Download and add 3 videos to the carousel (there already exist one) form pexel.com.
- Add dotted pagination to the bottom right of the carousel. Make sure this sits on top of the darkish grey background. This should be on the opposite side (right side) of the text "Welcome to pure life".
- Add the typing effect in the center of the carousel. It should type and erase three phrases. For now use Lorem Ipsum text. Restrain the text to a certain width so it doesn't span the entire screen.

**Comment by midas-kingme** [comment]
Taking ~
